config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'signup' => 'users#new'
  get 'sessions/new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  post 'add_skill' => 'users#add_skill'
  post 'like_skill' => 'users#like_skill'
  post 'hide_skill' => 'users#hide_skill'
  resources :skills
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :users_skill
  validates :name, presence: true, length: { maximum: 50 },
    uniqueness: true

  def self.findOrCreate(name)
    skill = Skill.find_by(name: name)
    if skill.nil?
      skill = Skill.!create(name: name)
    end
    return skill
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_skill
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  attr_accessor :remember_token
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
 
  # ユーザーログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/users_skill.rb
class UsersSkill < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
  has_many :users_skill_like
  validates :user_id, presence: true
  validates :user_id,  uniqueness: { scope: :skill_id }
  validates :skill_id, presence: true

  def like_users(user_id)
    usls = UsersSkillLike.where(users_skill_id: id)
    like_user_ids = []
    usls.each do |usl|
      like_user_ids.push(usl.user_id)
    end
    User.where(id: like_user_ids).limit(10)
  end
end

app/models/users_skill_like.rb
class UsersSkillLike < ActiveRecord::Base
  belongs_to :users_skill
  belongs_to :user
  validates :users_skill_id, presence: true
  validates :user_id, presence: true
  validates :users_skill_id,  uniqueness: { scope: [:users_skill_id, :user_id] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def show
    @skill = Skill.find(params[:id])
    user_ids = []
    users_skills = UsersSkill.where(skill_id: @skill.id, visible: true)
    users_skills.each do |us|
      user_ids.push(us.user_id)
    end
    @users = User.where(id: user_ids).paginate(page: params[:page])
    @skills = Skill.paginate(page: params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @users_skill = @user.users_skill.order("n_liked desc")
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 更新に成功したときの処理
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def add_skill
    @user = User.find(params[:user_id])
    skill = Skill.find_or_create_by(name: params[:add_skill])
    UsersSkill.find_or_create_by(user_id: @user.id, skill_id: skill.id)
    redirect_to @user
  end

  def like_skill
    @user = User.find(params[:user_id])
    if @user.id == current_user.id
      # 自分のページにいいねは出来ない
      flash[:danger] = "Cannot like a skill on your profile"
    else
      @skill = Skill.find(params[:skill_id])
      users_skill = UsersSkill.find_by(user_id: @user.id, skill_id: @skill.id)
      usl = UsersSkillLike.new(users_skill_id: users_skill.id, user_id: current_user.id)
      if usl.save
        # まだlikeしていない
        flash[:success] = "Liked skill!"
        users_skill.update(n_liked: users_skill.n_liked + 1)
      else
        # 既にlikeした
        flash[:success] = "Canceled like"
        UsersSkillLike.find_by(users_skill_id: users_skill.id, user_id: current_user.id).destroy
        users_skill.update(n_liked: users_skill.n_liked - 1)
      end
    end
    redirect_to @user
  end

  def hide_skill
    @user = User.find(params[:user_id])
    users_skill = UsersSkill.find(params[:users_skill_id])
    if @user.id == current_user.id
      users_skill.update(visible: !users_skill.visible)
    end
    if users_skill.visible
      flash[:success] = "Show #{ Skill.find_by(id: users_skill.skill_id).name }"
    else
      flash[:success] = "Hide #{ Skill.find_by(id: users_skill.skill_id).name }"
    end
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # beforeフィルター
  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  # ユーザーを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # 与えられたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Excercise", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>WantedlyExcercise</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>   
      <%= yield %>
    </div>
  </body>
</html>

app/views/skills/show.html.erb
<% provide(:title, @skill.name) %>
<h1><%= @skill.name %></h1>
<h3>Following users have this skill.</h3>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>

<%= will_paginate %>
</ul>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>

<%= will_paginate %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>

  <div class="col-md-8">
    <% if @user.users_skill.where(visible: true).any? || @user.id == current_user.id %>
      <h3>
        Skills (<%= @user.users_skill.where(visible: true).count %>)
      </h3>
      <% nth_skill = 0 %>
      <ol class="users_skills">
        <% @users_skill.each do |us| %>
          <% nth_skill += 1 %>
          <%= render partial: 'users_skills/users_skill', locals: { users_skill: us, nth_skill: nth_skill } %>
        <% end %>
      </ol>
    <% end %>
  </div>

  <div class="col-sm-3 col-md-offset-9">
    <%= form_tag add_skill_path, method: "post" do %>
      <div class="field">
        <%= text_field_tag :add_skill %>
      </div>
      <%= hidden_field_tag :user_id, @user.id %>
      <%= submit_tag "Add skill", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/users_skills/_users_skill.html.erb
<% skill = Skill.find(users_skill.skill_id) %>
<% if @user.id == current_user.id %>
  <li id="users_skill-<%= users_skill.id %>">
    <span class="name">
      <% like_btn_class =
        UsersSkillLike.exists?(users_skill_id: users_skill.id, user_id: current_user.id) ? "btn btn-success" : "btn btn-default" %>
      <%= link_to "#{ users_skill.n_liked } Liked", 
        like_skill_path({ user_id: @user.id, skill_id: users_skill.skill_id }), 
        method: :post, class: like_btn_class %>
      <%= link_to skill.name, skill%>

      <% hide_btn_text = users_skill.visible ? "Hide this skill" : "Show this skill" %>
      <%= link_to hide_btn_text,
        hide_skill_path({ user_id: @user.id, users_skill_id: users_skill.id }),
        method: :post, class: "btn btn-default"%>
  </span>
  <%= render partial: 'users_skills/who_liked', locals: { users_skill: users_skill , nth_skill: nth_skill} %>
  </li>
<% elsif users_skill.visible %>
  <li id="users_skill-<%= users_skill.id %>">
    <span class="name">
      <% like_btn_class = 
        UsersSkillLike.exists?(users_skill_id: users_skill.id, user_id: current_user.id) ? "btn btn-success" : "btn btn-default" %>
      <%= link_to "#{ users_skill.n_liked } Liked", 
        like_skill_path({ user_id: @user.id, skill_id: users_skill.skill_id }), 
        method: :post, class: like_btn_class %>
      <%= link_to skill.name, skill%>
    </span>
  <%= render partial: 'users_skills/who_liked', locals: { users_skill: users_skill , nth_skill: nth_skill} %>
  </li>
<% end %>

app/views/users_skills/_who_liked.html.erb
<% if nth_skill < 7 %>
  <br />
  <% users_skill.like_users(@user.id).each do |user| %>
    * <%= link_to user.name, user %>
  <% end %>
<% end %>

app/views/users_skills/show.html.erb
<% provide(:title, @users_skill.name) %>
<div class="row">
</div>